# Generated by Django 5.1.4 on 2024-12-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_created_at_tenant_created_by_tenant_status_and_more'),
        ('tickets', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('tenant', 'number')},
        ),
    ]
