# Generated by Django 5.1.4 on 2024-12-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_created_at_tenant_created_by_tenant_status_and_more'),
        ('tickets', '0004_alter_ticket_options_alter_ticket_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickettask',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='tickettask',
            name='number',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tickettask',
            unique_together={('ticket', 'number')},
        ),
    ]
