# Generated by Django 5.1.4 on 2025-01-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_tickettask_options_alter_tickettask_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='name',
            field=models.CharField(default='Attachment', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('assigned', 'Assigned'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketstatuschange',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('assigned', 'Assigned'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
