# Generated by Django 5.1.4 on 2025-01-01 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_created_at_tenant_created_by_tenant_status_and_more'),
        ('tickets', '0006_ticket_due_date_ticket_priority_ticket_resolution_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tasktype',
            unique_together={('tenant', 'name')},
        ),
    ]
