# Generated by Django 5.1.4 on 2025-01-10 23:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_tickettask_assigned_to_tickettask_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettask',
            old_name='task',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='tickettask',
            old_name='dateTime',
            new_name='date_worked',
        ),
        migrations.AlterField(
            model_name='tickettask',
            name='hours_worked',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AlterField(
            model_name='tickettask',
            name='minutes_worked',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
    ]
