# Generated by Django 5.1.4 on 2024-12-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent'), ('supervisor', 'Supervisor'), ('customer', 'Customer')], default='customer', max_length=50),
        ),
    ]
