# Generated by Django 5.1.4 on 2024-12-31 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('tenants', '0003_tenant_created_at_tenant_created_by_tenant_status_and_more'),
        ('users', '0003_customtoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomToken',
            new_name='TenantToken',
        ),
    ]
